
test('should not fail', () => { 
  // no throw error
})